name: Harttle Land
url: http://harttle.github.io

permalink: /:year/:month/:day/:title.html

paginate: 4
paginate_path: "page:num"

highlighter: pygments

markdown: redcarpet
markdown_ext:  md
redcarpet:
    extensions: [no_intra_emphasis,tables,autolink,disable_indented_code_blocks,fenced_code_blocks]

exclude: ['README.md', '*.sh', '.*', 'scripts/']

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

cate_icons:
  reading: "fa-book"
  linux: "fa-linux"
  web: "fa-html5"
  misc: "fa-file-text"
